# This is a basic workflow to help you get started with Actions
name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          persist-credentials: false

    # Runs a set of commands using the runners shell
    # In this case the build op is just copying a bunch of files
    - name: Build
      run: |
        rm -rf build-working-dir
        mkdir build-working-dir
        cp -r static/* build-working-dir/
    
    # We are sure the build completed successfully, replace the previous deployment
    - name: Move
      run: |
        rm -rf deploy
        mv build-working-dir deploy

    # Deploy to github pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: deploy   # The folder the action should deploy.
